### ISSUE TITLE
[CRASH] Optigui causing crash for some reason

### ISSUE THREAD

**Issue by Cowllum** [opekope2/OptiGUI#100]
### Loader and its version

Fabric Loader 0.15.11

### OptiGUI version

2.1.7

### Steps to reproduce

I launched the game with my personal modpack (consisting of Fabulously Optimized and Cobblemon Fabric combined) then it crashes.

### Game logs

https://mclo.gs/T7VRWlm

**Comment by opekope2** [comment]
Kind of similar to #80 and FabricMC/fabric-language-kotlin#120. Maybe JetBrains reverted that change.
This is a Kotlin/FLK issue, report it at https://github.com/FabricMC/fabric-language-kotlin. In the meanwhile, try downgrading Fabric Language Kotlin to 1.10.2 (Kotlin 1.9.24)

**Comment by opekope2** [comment]
Can't reproduce

**Comment by opekope2** [comment]
Cobblemon bundles Kotlin 1.8.20 for some reason instead of depending on FLK or JAR-in-JAR'ing it. This causes serious compatibility issues. Download a matching version of Fabric Language Kotlin (the one with Kotlin 1.8.22 seems to work).
