### ISSUE TITLE
[BUG] Conquest_ resourcepack GUI not working

### ISSUE THREAD

**Issue by dom1643** [opekope2/OptiGUI#101]
### Expected Behavior

The Conquest_ resourcepack has a custom GUI that works with Optifine and should work with OptiGUI.

### Actual Behavior

The pack's GUI does not work with OptiGUI, though font and some textures like the main menu title are functioning.

### Steps To Reproduce

[Download and enable the resourcepack.](https://www.curseforge.com/minecraft/texture-packs/conquest_/files/4857510)

### Loader and its version

Fabric Loader 0.15.11

### OptiGUI version

2.3.0-beta.2+1.20.5

### Behavior difference

- [ ] OptiGUI documentation
- [ ] OptiFine
- [ ] Something you logically expect from OptiGUI
- [x] Doesn't work at all

### Anything else

This is on 1.20.6.

**Comment by opekope2** [comment]
The resource pack does not have any OptiFine-specific `/assets/minecraft/optifine/gui/container/*.properties` files. Maybe another resource pack overrides the GUI, even if it's below Conquest_ or even Vanilla. Try disabling other resource packs.

**Comment by dom1643** [comment]
The resource pack isn't being overwritten by anything, the GUI doesn't appear even if it's the only pack enabled and is at the very top. I figured it could have been a mod I had enabled that may be messing with the GUI in some way, but other packs with their own GUIs function fine (in hindsight, not sure why I assumed this to be an OptiGUI bug). I still did disable any mods that may or do affect the GUI in any way to check, and the pack still did not work.
This is probably an issue with the resource pack itself.

**Comment by opekope2** [comment]
Kinda works on my machine, but these are "vanilla" textures, and not OptiFine/OptiGUI ones.
![Shulker box](https://github.com/opekope2/OptiGUI/assets/20487556/a2178725-6634-4c88-b9ee-87ca5312e8a7)
![Inventory](https://github.com/opekope2/OptiGUI/assets/20487556/ca7fb7b5-13b3-4038-a73e-1c3308c8e077)
