### ISSUE TITLE
[BUG] <MC Parks Disney World shirt textures don't work>

### ISSUE THREAD

**Issue by MooMooMcDoo** [opekope2/OptiGUI#107]
### Expected Behavior

MC Parks has custom shirts. They should look like t shirts with designs on them that can be purchased using in game currency earned from doing park activities

### Actual Behavior

Shirts just appear as leather armor

### Steps To Reproduce

Enter any shop on the server with t shirts for sale

### Loader and its version

fabric 0.58.0+1.19

### OptiGUI version

2.1.7

### Behavior difference

- [ ] OptiGUI documentation
- [X] OptiFine
- [X] Something you logically expect from OptiGUI
- [ ] Doesn't work at all

### Anything else

seems that everything else on the server doesn't have any issues. the shirts do function with optifine

**Comment by opekope2** [comment]
Can you explain how this is an OptiGUI issue? OptiGUI is for custom GUI textures, not armor models.

**Comment by MooMooMcDoo** [comment]
Oh man, you're so right. When I installed this mod, the server prompted me
to download the texture pack, and I thought I found my solution. Thank you
for your work anyways, and if you know of mod that actually does that, you
know where to find the dummy looking for it.

**Comment by opekope2** [comment]
You may want to take a look at [OptiFine Alternatives](https://optifine.alternatives.lambdaurora.dev/).
