### ISSUE TITLE
[CRASH] Crash with mod menu and map atlases

### ISSUE THREAD

**Issue by Ch4mp10** [opekope2/OptiGUI#108]
### Loader and its version

Fabric Loader 0.15.10

### OptiGUI version

2.1.7

### Steps to reproduce

Opened config file for map atlases through nod menu and game crashed before entering config menu

### Game logs

[crash-2024-08-03_20.06.02-client.txt](https://github.com/user-attachments/files/16484327/crash-2024-08-03_20.06.02-client.txt)
[crash-2024-08-03_20.17.40-client.txt](https://github.com/user-attachments/files/16484339/crash-2024-08-03_20.17.40-client.txt)
[crash-2024-08-03_20.21.05-client.txt](https://github.com/user-attachments/files/16484340/crash-2024-08-03_20.21.05-client.txt)

### Anything else

Tried latest release ver of mod menu instead of beta
Tried 2.1.6 of optigui

**Comment by opekope2** [comment]
Minecraft 1.19.2 support will not be updated this year
