### ISSUE TITLE
animated fox guis

### ISSUE THREAD

**Issue by kowai-kaizen** [opekope2/OptiGUI#118]
### Expected Behavior

in the resource pack "animated fox guis", the texture of the fox should change depending on the biome in which you are located

### Actual Behavior

the texture does not change

### Steps To Reproduce

I checked only with the above resource pack and this list of installed mods:
advancement info; animatica; apple skin; auto-clicker; axiom; better f1; better f3; better stats; c2me; chat heads; cicada; cit resewn; click throught 2.0; cloth config; continuity; enchanted block entities; entity culling; emf; etf; fabric api; fabric language kotlin; fabric sky boxes; ferrit core; flashback; held item info; immediately fast; invidium; inventory hud; iris; item scroller; jade; kiwi; language reload; libjf; litematica sakura; lithium; loading backgrounds; malilib; minihud; mod menu; model fix; modern fix; more culling; noisium; notes; nvidium; optigui 2.3.0 beta.5+1.21; peek; polytone; puzzle; reeses sodium options; rp renames; shulker box tooltip; simple shulker preview; skin layers 3d; sodium extra; sodium; symbol; tcd commands; thread tweak; tweakeroo; ukulib; ukus armor hud; xaeros minimap; xaeros world map; yet another config

### Loader and its version

0.16.5

### OptiGUI version

optigui 2.3.0 beta.5+1.21

### Behavior difference

- [ ] OptiGUI documentation
- [X] OptiFine
- [ ] Something you logically expect from OptiGUI
- [ ] Doesn't work at all

### Anything else

The resource pack is working properly with the optifine

**Comment by opekope2** [comment]
OptiFine `texture.PATH` is apparently broken in every 2.3.0 release
