### ISSUE TITLE
[BUG] Colorful Containers dyed shulker boxes lose their color GUI texture in 1.21.4

### ISSUE THREAD

**Issue by cramoraint** [opekope2/OptiGUI#124]
### Expected Behavior

This works correctly in 1.21.3 with version OptiGUI 2.3.0-beta.6+1.21.2 and latest version of colorful containers from https://modrinth.com/resourcepack/colourful-containers-gui
![lime](https://github.com/user-attachments/assets/24be2b3f-41d9-44cd-a7c2-dda6b8b6a6ef)

### Actual Behavior

Using the same version of OptiGUI and colorful containers in 1.21.4 makes shulker boxes have the default shulker box texture.
![image](https://github.com/user-attachments/assets/ef77c915-ff76-440c-9e6a-c128f36cdc35)

### Steps To Reproduce

Install the latest version of OptiGUI 2.3.0-beta.6+1.21.2 and colorful containers resource pack from https://modrinth.com/resourcepack/colourful-containers-gui/versions and the dyed shulker boxes do not contain the colored guis like they do when using the same version of OptiGUI and colorful containers in version 1.21.3

### Loader and its version

Fabric Loader 0.16.9

### OptiGUI version

OptiGUI 2.3.0-beta.6+1.21.2

### Behavior difference

- [ ] OptiGUI documentation
- [ ] OptiFine
- [ ] Something you logically expect from OptiGUI
- [x] Doesn't work at all

**Comment by opekope2** [comment]
Looked into it, Mojang changed rendering. Should be an easy fix, which should be compatible with older Minecraft versions.
I removed 1.21.4 from Modrinth and CurseForge.

**Comment by opekope2** [comment]
Fixed in 2.3.0 beta 7
