### ISSUE TITLE
[Bug] you need to click twice to get the crafting output from crafting table with Rybo's Enhanced GUI

### ISSUE THREAD

**Issue by EGOIST1372** [opekope2/OptiGUI#17]
you need to click twice to get the crafting output from crafting table with Rybo's Enhanced GUI
since you mentioned that Rybo's Enhanced GUI is fully supported I got it and here we go I found a bug
everytime I want to craft something and grab the output I need to double click on output of the crafting table to grab the output
If I click once it won't get selected (I always use SHIFT + click for getting the output faster to my inventory)
I hope you can reproduce and fix the issue
thanks in advance <3

**Comment by EGOIST1372** [comment]
@opekope2 it seems that this issue got solved in v2.0.0 alpha3 (I was using the v1.1.6)
you can close this issue as soon as you release it as stable version

**Comment by opekope2** [comment]
Closing, as the first beta should be stable enough.
