### ISSUE TITLE
Crash when trying to sleep in a bed

### ISSUE THREAD

**Issue by stantios** [opekope2/OptiGUI#20]
Loader: Quilt
Quilt Loader Version: 0.18.3
QFAPI / QSL Version: QFAPI 5.0.0-beta.8 and QSL 4.0.0-beta.12
Log: https://mclo.gs/zRQ8xbF

Description: I tried to sleep in a bed and then suddenly my game crashed, I looked in the logs and saw that either OptiGUI or Tweakeroo was causing it, so I first removed OptiGUI to see if the crash had been fixed and I could sleep in a bed and I found that it was OptiGUI causing the crash.

**Comment by opekope2** [comment]
That's interesting, because I have no idea where `field_25114` comes from.
The loaded OptiGUI is built from the old codebase, which is being replaced by the new one in this repo.
The next release will be the first beta, with Quilt support. I'll definitely test beds too.

**Comment by opekope2** [comment]
I can't reproduce it with your configuration on my machine. `field_25114` is not found in the disassembly. Let me know if it was a one-time crash, or it crashed multiple times.
