### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by voidrinix** [opekope2/OptiGUI#24]
Here is the [crash log](https://mclo.gs/VDJVx8C)

**Comment by opekope2** [comment]
Can confirm. Doesn't work with fabric either. Seems like Minecraft 1.19.4 changed `net.minecraft.GameVersion`, which continues to be source-compatible, but is binary-incompatible. And I didn't notice this. I'll mark this version as incompatible with 1.19.4, and fix it in beta 2.
I'll close this as soon as it gets released.

**Comment by opekope2** [comment]
Fixed in beta 2
