### ISSUE TITLE
Can you mark OptiGlue as library in mod menu?

### ISSUE THREAD

**Issue by voidrinix** [opekope2/OptiGUI#29]
![изображение](https://user-images.githubusercontent.com/73175330/229375677-d92bffba-50d0-4947-acdb-f1f052750560.png)
For example, like this:
![изображение](https://user-images.githubusercontent.com/73175330/229375762-56e789bd-e332-438a-b5aa-3a9fb1b5867f.png)

**Comment by opekope2** [comment]
Good catch, just before the full release, thanks.

![image](https://user-images.githubusercontent.com/20487556/229380933-f9c1523e-379a-4f78-81e1-c10c634d14e3.png)

I made OptiGlue show up under OptiGUI. I'll push it soon.
