### ISSUE TITLE
Suggestion: skeleton horse variant support

### ISSUE THREAD

**Issue by Vi-Tul** [opekope2/OptiGUI#31]
If there is already a support for this, pls explain properties

**Comment by opekope2** [comment]
While it is documented [here](https://opekope2.github.io/OptiGUI-Next/format/#variants_3), this feature is being reworked in beta 4.

The current behavior is:
```properties
container=horse
variants=_skeleton_horse
texture=<replacement.png>
```

The rework will be on the [`dev-properties-rework`](https://github.com/opekope2/OptiGUI-Next/tree/dev-properties-rework) branch, which will be merged into `dev`. This rework will be a breaking change.

**Comment by opekope2** [comment]
The rework will still support everything (most things) OptiFine supports, but will add a new OptiGUI syntax for more advanced scenarios.

The new skeleton horse syntax is planned to be:
```ini
[skeleton_horse]
texture=<replacement.png>
```

**Comment by Vi-Tul** [comment]
Thanks for the quick reply!

**Comment by opekope2** [comment]
You can track the progress of the rework in #32, and when beta 4 gets released, don't forget to check [the documentation](https://opekope2.github.io/OptiGUI-Next) to learn how it works.
