### ISSUE TITLE
Crash NoSuchMethodError

### ISSUE THREAD

**Issue by ClaudiusMinimus** [opekope2/OptiGUI#34]
While testing my newly ported and unpublished fabric pack, Create Conquest Arcane I was out exploring in my Chest Boat. I opened the inventory and the client crashed (see attached [crash report](https://github.com/opekope2/OptiGUI-Next/files/11213012/crash-2023-04-12_09.10.11-client.txt))

Minecraft 1.19.2
Fabric 0.14.18
OptGUI 2.0.0-beta.3
[CCA 0.3.0 ALPHA](https://github.com/ClaudiusMinimus/CCA_Fabric/raw/development-1.19.2/builds/CCA%20Fabric%20ALPHA-0.3.0.zip) You can test this yourself if you like. Place a chest boat in water, enter it, then open the chest. I used a black oak chest boat 

[crash-2023-04-12_09.10.11-client.txt](https://github.com/opekope2/OptiGUI-Next/files/11213012/crash-2023-04-12_09.10.11-client.txt)

## Mod List
Animatica
AppleSkin
Architectury API 
ArdaGrass
Bad Wither No Cookie - Reloaded
Balm 
Better Combat 
Better Compatibility Checker
BisectHosting Server Integration Menu 
Bookshelf
Borderless Mining
Botania 
Botania: Garden of Glass
Building Wands
Cardinal Components
Carry On
CIT Resewn
CleanCut
Client Tweaks 
Cloth Config API 
Clumps
Colormatic
Conquest Reforged Recipes
Conquest Reforged
Continuity
Controlling
Crafting Tweaks 
Create Crafts & Additions
Create Deco Fabric
Create Fabric
Cull Less Leaves
Drippy Loading Screen 
Easy Emerald Tools & More 
Enchantment Descriptions
Enhanced Mob Spawners
Entity Culling Fabric/Forge
Essential Commands
EssentialGUI
Extreme sound muffler  Official
Fabric API
Fabric Language Kotlin
FabricSkyboxes
FancyMenu 
Farmer's Delight 
Fastload
FerriteCore 
Forge Config API Port 
FTB Backups 2
FTB Chunks 
FTB Library 
FTB Quests 
FTB Ranks 
FTB Teams 
GeckoLib
Gravestones
Grind Enchantments
Harvest with ease
Here be no Dragons!
ImmediatelyFast
Indium
Inventory Sorting
Iris Shaders
Item Filters
Just Enough Items 
Kibe Utilities
Kiwi
Konkrete 
KubeJS Botania
KubeJS Create
KubeJS
Language Reload
LazyDFU
Leaves Be Gone
Light Overlay 
Lighting Wand
Lithium 
Lootr 
MaLiLib
MC Dungeons Weapons
MemoryLeakFix
MmmMmmMmmMmm 
Mod Menu
Moonlight Lib
Mouse Tweaks
Mythic Metals
Mythic Mounts
NetherPortalFix 
No Chat Reports
OptiGUI
oωo (owo-lib)
Patchouli 
playerAnimator
PolyLib
Polymorph 
Ponder for KubeJS
Puzzles Lib 
Reese's Sodium Options
Resource Tools 
Rhino
Smooth Boot 
Sodium Extra
Sodium
Spirit
Starlight 
Tempad
Tom's Simple Storage Mod 
ToolTipFix
Traveler's Backpack 
Trinkets 
Tweakeroo
Waystones 
Xaero's Minimap
Xaero's World Map
YetAnotherConfigLib
Your Options Shall Be Respected 
YUNG's API 
YUNG's Better Desert Temples 
YUNG's Better Dungeons 
YUNG's Better Mineshafts 
YUNG's Better Nether Fortresses 
YUNG's Better Ocean Monuments 
YUNG's Better Strongholds 
YUNG's Better Witch Huts

**Comment by opekope2** [comment]
This is similar to #33. As I mentioned there, this code path will be replaced in beta 4.
When I was experimenting with OptiGlue, I thought Minecraft will break less, but I was wrong. Supporting multiple Minecraft versions is not an easy task (especially because every toolkit breaks whenever it wants to), the only way to avoid these errors is building OptiGUI for each version (which may only be the latest) or move every Minecraft-related code to OptiGlue.
This breakage was introduced in alpha 6 by a rename in loom mappings in 1.19.3. I'll mark as incompatible with older versions as usual later...

**Comment by ClaudiusMinimus** [comment]
Thanks for the update! I hope the information was useful!
And I look forward to the next update.

**Comment by opekope2** [comment]
I updated the affected versions on Modrinth and CurseForge. Alpha 5 seems to be the best working version after 1.1.6 lol

**Comment by ClaudiusMinimus** [comment]
Sweet! I'll test it on Friday and let you know how it goes. Thanks!

**Comment by opekope2** [comment]
Sorry for the misunderstanding, I only updated the supported Minecraft versions of the affected OptiGUI versions, removing the crashing Minecraft versions.

**Comment by ClaudiusMinimus** [comment]
Actually, it works fine with 1.19.2 as shown below. No crash :smile: 
Thanks! CM
![image](https://user-images.githubusercontent.com/17887664/232100134-cf5948cc-9abc-42ef-8c4d-3e7f3529807e.png)

**Comment by opekope2** [comment]
Java moment
