### ISSUE TITLE
[Bug] OptiGUI replaces barrel texture with chest texture

### ISSUE THREAD

**Issue by JustAHuman-xD** [opekope2/OptiGUI#36]
### Expected Behavior
The barrel texture remains the default inventory texture instead of getting changed to the chest texture

### Steps to Reproduce
1. [Download the latest Colorful Containers](https://www.planetminecraft.com/texture-pack/colourful-containers-dark-mode-gui-optifine-required/)
2. Join Singleplayer or Multiplayer World
3. Place and Open a Barrel
4. Observe GUI

### Difference in Behavior
Selection: `Optifine`

- [x]  I have searched for existing issues

**Comment by JustAHuman-xD** [comment]
This is however related to #30 
I just felt that it wasn't really the same issue. As in Optifine it is the barrel texture with no changes necessary but OptiGUI it is the chest texture

**Comment by opekope2** [comment]
#32 should fix it, but I'll take a look soon (sometime this week... probably)

The reason why OptiGUI would replace the barrel texture is that the texture pack didn't explicitly tell it not to (by specifying `_barrel=false`). This is obviously wrong and was changed in the rework.

**Comment by JustAHuman-xD** [comment]
Go it! In any case thank you for creating this mod in the first place. It is a very nice one!
