### ISSUE TITLE
Book Gui Available? Suggestion: Change book Gui depending on the book NBT in player's hand. Or on Lectern NBT.

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/OptiGUI#38]
Hi, 
Thanks for your great mod. 

I read the wiki. And didn't find the answer. If there is anything I can do with the GUI book now, please tell me.

I saw that NBT raw is not supported at the moment, but if they ever come out. Then there is a suggestion. Add functionality that would read the NBT of the book in the hand and change its GUI texture based on that. Or that it reads NBT Lectern on which the book lies.
![book](https://github.com/opekope2/OptiGUI-Next/assets/70120313/b13753a3-2ec2-4a58-ba3e-8f7cef36ba22)

**Comment by opekope2** [comment]
At the moment, only the GUI of blocks or entities are supported, not items. The properties rework (#32) indirectly added support for lecterns, but only [general properties](https://opekope2.github.io/OptiGUI-Next/format/#general-properties) are supported (as of now).

I am not planning to add NBT support as of now, but I'm planning to add a `comparator.output` property in the future. A `book.page` property would also be a good idea (in a future version).

**Comment by opekope2** [comment]
Upon investigating the source code, I found that it "shouldn't work", because the texture path of the lectern isn't included in TexturePath.kt, thus won't be found in InteractionHandler.kt

**Comment by opekope2** [comment]
Bruh I didn't mean to close it
Also, there are some sneak peeks about the future selectors in the [documentation](https://opekope2.github.io/OptiGUI/format.html#book)

**Comment by SoulxluoS** [comment]
Сool.
