### ISSUE TITLE
'Unique Dark' Support

### ISSUE THREAD

**Issue by potav** [opekope2/OptiGUI#39]
https://modrinth.com/resourcepack/unique-dark
https://www.curseforge.com/minecraft/texture-packs/unique-dark

This seems to be very similar to Colourful Containers, but it doesn't work with OptiGUI.

**Comment by opekope2** [comment]
It's a vanilla resource pack (the free version) and works for me. Can you explain what doesn't work?

**Comment by potav** [comment]
I missed that I had to pay for shulker GUI version. I'm sorry.
