### ISSUE TITLE
[CRASH] 2.1.0 incompatible with quilt 1.19.2

### ISSUE THREAD

**Issue by Rozbiynk** [opekope2/OptiGUI#42]
### Steps to reproduce

Download OptiGUI 2.1.0 beta
Download Quilt Kotlin Libraries 1.0.2
Download QFAPi 4.0.0 beta 30

### Game logs

https://mclo.gs/U8byp09

**Comment by opekope2** [comment]
Seems like 202a76d broke it. The required QKL version is not yet released.
