### ISSUE TITLE
[BUG] shulker box display with tweakeroo

### ISSUE THREAD

**Issue by Rozbiynk** [opekope2/OptiGUI#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Display correct background for shulker

### Steps To Reproduce

Enable shulker box display in tweakeroo
Enable colorful containers
Notice that shulker use background of inventory

### Behavior difference

Both

### Anything else

![изображение](https://github.com/opekope2/OptiGUI/assets/95433246/4fa11213-cc4c-45d2-8eea-21a38dec8f81)
![изображение](https://github.com/opekope2/OptiGUI/assets/95433246/f914ca87-37a3-4232-9a40-93b8015d8199)
![изображение](https://github.com/opekope2/OptiGUI/assets/95433246/8afe1eab-0a2c-4f6b-9ec0-9601e409449f)
happend on latest beta

**Comment by opekope2** [comment]
I suspect that you also have this issue when you open your player inventory (but it's uglier).
My first guess it's that I forgot to add a check for the original texture so it's replacing every container's texture specified in the resource pack (because I didn't test tooltip mods)

**Comment by Rozbiynk** [comment]
> when you open your player inventory

what do you mean? in inventory everything is okay

**Comment by opekope2** [comment]
Okay that's cool. I suspected that every inventory screen had that problem but nope

**Comment by opekope2** [comment]
Seems like 7823745 fixed it
