### ISSUE TITLE
[BUG] stable version of OptiGUI

### ISSUE THREAD

**Issue by notIkibo** [opekope2/OptiGUI#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

![image](https://github.com/opekope2/OptiGUI/assets/106886638/ffca24ff-b041-4992-be35-a72096ea360e)

### Steps To Reproduce

Have 1.19.2, have newest update, start

### Behavior difference

OptiGUI documentation

**Comment by opekope2** [comment]
Are you using Fabric or Quilt loader?

**Comment by notIkibo** [comment]
Fabric

**Comment by opekope2** [comment]
This looks like a loader issue. At this point, Fabric is solving the dependencies of the mods to load. It should pick up OptiGlue 1.19, but for some reason, it picks up 1.19.3. I'll ask the Fabric devs sometime.

**Comment by opekope2** [comment]
Weird, I can't reproduce with Prism Launcher. This is a snippet from my log. It loads the correct version of OptiGlue.
![image](https://github.com/opekope2/OptiGUI/assets/20487556/14a69bcc-9ba5-4730-82be-04db667eacee)
Try it with a fresh profile to see if it works.

**Comment by notIkibo** [comment]
So sorry, I completely forgot to respond. It worked. I think at that point there was already the next update, but it works just fine now. Thank you for responding :)
