### ISSUE TITLE
[BUG] quilt incompatible

### ISSUE THREAD

**Issue by Rozbiynk** [opekope2/OptiGUI#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

load xd

### Steps To Reproduce

![изображение](https://github.com/opekope2/OptiGUI/assets/95433246/1b044772-f6b2-44d2-b477-9911df9f7ceb)
also affect 1.18.10 loader 

### Behavior difference

OptiGUI documentation

**Comment by opekope2** [comment]
Welp
Seems like quilt hasn't updated it's fabricloader implementation yet
I'll probably need to downgrade it (again), which should be easy (java foreshadowing)
