### ISSUE TITLE
[BUG] How it works for Barrel? And other containers.

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/OptiGUI#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

![image](https://github.com/opekope2/OptiGUI/assets/70120313/991a1e4a-ac27-434d-ac59-b0e51d79afe9)

### Actual Behavior

It doesn't work in practice.
![image](https://github.com/opekope2/OptiGUI/assets/70120313/d5a9267b-4a15-4b87-81ce-b241f1b709d8)

### Steps To Reproduce

![image](https://github.com/opekope2/OptiGUI/assets/70120313/2b6dd28e-869b-427b-b028-822475191cc7)

### Loader and its version

quilt-loader-0.19.2-1.20.1

### OptiGUI version

2.1.3

### Behavior difference

- [X] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

### Anything else

If there is something I don't understand, please explain how.

There may be a line missing here with Barrel.
![image](https://github.com/opekope2/OptiGUI/assets/70120313/d02d4918-8292-4b3f-bdeb-7149c3094511)

**Comment by SoulxluoS** [comment]
Same question on Zombie Horse, Skeleton Horse, Chest Boat, Chest Minecart and Trader Llama.

**Comment by opekope2** [comment]
Your are looking at the OptiFine resource loader code, which converts OptiFine properties to OptiGUI INI. OptiFine has no support for barrels, so writing `container=barrel` won't work.
What you have to do is create a file in `/assets/optigui/gui/` (for example, `/assets/optigui/gui/barrel.ini`, and do the following, as written in the docs:

```ini
[barrel]
texture=barrel.png
```

Do not forget the PNG extension.
For chest boats, here's my [resource pack](https://modrinth.com/resourcepack/chest-boat-gui)

**Comment by SoulxluoS** [comment]
Ok, thank you.
Now I get it. It works.

**Comment by opekope2** [comment]
Btw, you found a spooky scary Easter egg in the OptiFine converter code :wink:
