### ISSUE TITLE
[Features] Horse and Llama Color-types

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/OptiGUI#60]
Possible implementation option:

For Horse 
![image](https://github.com/opekope2/OptiGUI/assets/70120313/86ed3b8d-0d4b-4bb3-a89d-7de66c230b84)
![image](https://github.com/opekope2/OptiGUI/assets/70120313/bfd9e0c1-c8bd-41d4-80a5-03270782e9fe)

For Llama
![image](https://github.com/opekope2/OptiGUI/assets/70120313/9e8e4a57-333b-4d38-a109-5291feb5a62b)
![image](https://github.com/opekope2/OptiGUI/assets/70120313/3b497659-88af-48fc-8ca6-1f5b8563991a)

**Comment by SoulxluoS** [comment]
Correct for OptiGUI format⭐

Horse
![](https://user-images.githubusercontent.com/70120313/253671001-86ed3b8d-0d4b-4bb3-a89d-7de66c230b84.png)
![image](https://github.com/opekope2/OptiGUI/assets/70120313/f38fe79a-8fb5-4856-8eb1-36be6b06ed5e)


Llama
![](https://user-images.githubusercontent.com/70120313/253668098-9e8e4a57-333b-4d38-a109-5291feb5a62b.png)
![image](https://github.com/opekope2/OptiGUI/assets/70120313/6a699b3f-cb2f-4390-83fc-64e7c16add87)

**Comment by opekope2** [comment]
Good idea, I'll work on it in the 2.2.1 update. There are never enough selectors :grin:

**Comment by opekope2** [comment]
There are [horse markings](https://maven.fabricmc.net/docs/yarn-1.20.1+build.10/net/minecraft/entity/passive/HorseMarking.html) alongside [horse variants](https://maven.fabricmc.net/docs/yarn-1.20.1+build.10/net/minecraft/entity/passive/HorseColor.html), I'll implement them, too.

**Comment by SoulxluoS** [comment]
👍

**Comment by opekope2** [comment]
I'll implement these in 2.2.0-alpha.1 to avoid introducing breaking changes in 2.2.1.
The horse variant looks like Mojmap (yarn is HorseColor).
The selector will be `horse.colors`, to not confuse with `variants` in OptiFine properties.

**Comment by SoulxluoS** [comment]
hype, thank you for your work
