### ISSUE TITLE
[BUG] [trader_llama] not work

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/OptiGUI#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

[trader_llama] work for Trader Llama

### Actual Behavior

[trader_llama] not work for Trader Llama

[llama] work for Llama

[llama trader_llama] work for Llama & Trader Llama

### Steps To Reproduce

![image](https://github.com/opekope2/OptiGUI/assets/70120313/7e0b90ad-645a-4cff-98c0-8853f36f3ef6)

### Loader and its version

quilt-loader-0.19.2-1.20.1

### OptiGUI version

2.1.3

### Behavior difference

- [X] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
Can confirm in my latest working tree, looks like I forgot to specify the default texture of trader llama

**Comment by SoulxluoS** [comment]
hype, thank you for your work
