### ISSUE TITLE
[CRASH] Crash on startup 1.18.2

### ISSUE THREAD

**Issue by HaXrDEV** [opekope2/OptiGUI#62]
### Loader and its version

Fabric loader 0.14.21

### OptiGUI version

optigui-2.1.3

### Steps to reproduce

Updated the mod from optigui-2.1.2 to optigui-2.1.3. The latest version causes the game to crash immediately on startup throwing the crash log provided.

Reverting to the older version fixes the issue.

### Game logs

https://mclo.gs/9vDHB5g

### Anything else

Note that I was experiencing this issue on my modpack called 'Insomnia: Hardcore'. I don't know if this is caused by an incompatibility or not, since I have not tested it on its own.

**Comment by SplendidAlakey** [comment]
Same on 1.19.2. Doesn't appear to be an incompatibility, since it's referencing a missing class.

**Comment by opekope2** [comment]
Uhh, frick. That's the hanging sign. Yeah I forgot to check Minecraft version again :skull:

**Comment by opekope2** [comment]
I moved hanging signs to OptiGlue 1.19.3 (where other 1.20 features are).
I'll release a quick hotfix update after having some sleep

**Comment by opekope2** [comment]
I'll look into testing for this type of crash in the future. A hotfix should be available soon.
