### ISSUE TITLE
[BUG] <crashes on 2.1.4 for 1.19.2>

### ISSUE THREAD

**Issue by Aces-and-Jacks** [opekope2/OptiGUI#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

No crash

### Actual Behavior

Crash

### Steps To Reproduce

load in

### Loader and its version

Quilt 0.19.2

### OptiGUI version

2.1.4

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

### Anything else

https://mclo.gs/Z6OQ25N

**Comment by opekope2** [comment]
Oh fugg, I forgor this code :skull:
Use 2.1.2 until I fix it real quick

**Comment by opekope2** [comment]
All I had to do was to log into a world, yet I only made to the title screen and hadn't found the bug. I'll release it when Java stops hating me
