### ISSUE TITLE
Minecraft 1.20.2

### ISSUE THREAD

**Issue by opekope2** [opekope2/OptiGUI#75]
OptiGUI 2.1.5 codebase doesn't support Minecraft 1.20.2, because the villager GUI texture was changed (and maybe some other APIs).
I tried compiling 2.1.5 for Minecraft 1.20.2, but Java/Gradle/Loom/FAPI had skill issue, and if it compiled, FAPI crashed the game. I hate java when it does this to me.
OptiGUI 2.2.0 codebase doesn't support Minecraft 1.20.2, because Toast and DrawContext abstractions are not yet implemented in LiLaC (oh boy, it's complicated).
I may try again to port 2.1.5 to Minecraft 1.20.2 sometime in the future. I have more important IRL stuff, and some burnout.
ETA? 2024, probably. But *maybe* earlier.

**Comment by SoulxluoS** [comment]
Okay, thank you)
Have a nice vacation from the code)

**Comment by bstlyc** [comment]
pls update 👍

**Comment by ZoeLunar** [comment]
Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!

**Comment by Madis0** [comment]
> Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!

There are no releases or commits made today, perhaps you just got confused by the availability of the alpha build (for 1.20.1)?

That said, I discovered that (stable version of) the mod does actually run on 1.20.2 without crashing, if you do some trickery to override the required Minecraft version :stuck_out_tongue:

**Comment by ZoeLunar** [comment]
> > Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!
> 
> There are no releases or commits made today, perhaps you just got confused by the availability of the alpha build (for 1.20.1)?
> 
> That said, I discovered that the mod does actually run on 1.20.2 without crashing, if you do some trickery to override the required Minecraft version 😛

Can you please teach this very noob/tech illiterate person on how to do this? hahah

**Comment by Madis0** [comment]
> Can you please teach this very noob/tech illiterate person on how to do this? hahah

Well, the restrictions exist for a reason - to not overwhelm the dev with support requests in case something _does_ break. For example, villager GUIs indeed look wonky, as stated in the OP.

That said, non-noobs can look up and follow [a certain tutorial](https://lmddgtfy.net/?q=fabric%20override) and noobs can follow the updates for a certain popular modpack ᵒⁿ ᵐʸ ᵖʳᵒᶠᶦˡᵉ.

**Comment by opekope2** [comment]
> > Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!
> 
> There are no releases or commits made today, perhaps you just got confused by the availability of the alpha build (for 1.20.1)?
> 
> That said, I discovered that (stable version of) the mod does actually run on 1.20.2 without crashing, if you do some trickery to override the required Minecraft version :stuck_out_tongue: 

Mojang changed the villager texture path in 1.20.2 (`villager2.png` -> `villager.png`), and [here's why OptiGUI 2.1.5 doesn't support it](https://github.com/opekope2/OptiGUI/blob/9e5e3f27d4048e011532de20a2ae0b217e615f5b/OptiGUI/src/main/kotlin/opekope2/util/TexturePath.kt#L107). This code has been replaced with a modular one in the latest alpha, which enables different default textures based on the current version of Minecraft or other mods.

**Comment by opekope2** [comment]
> Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!

Synergy server updated to 1.20.2, and I focus on university and related stuff. I may try to make a 1.20.2 build of 2.1.5 this year again or just edit the bytecode if the dev env breaks again, just as the founding fathers intended 😂

I noticed an improvement in my mental health after taking a break from OptiGUI development.

I want to add automatic tests to OptiGUI 2.2.0 to make sure that all features work properly, and it doesn't crash (all of which happened in the past). This will take time. Editing 2.1.5 is easy, if the dev env doesn't break (last time, it did)

That being said, thank you for your patience.

**Comment by ZoeLunar** [comment]
> > Good afternoon! Do we have any news on this? My curseforge indicates that this was updated today, but I did not saw any news, so I hope its not a bother to ask!
> 
> Synergy server updated to 1.20.2, and I focus on university and related stuff. I may try to make a 1.20.2 build of 2.1.5 this year again or just edit the bytecode if the dev env breaks again, just as the founding fathers intended 😂
> 
> I noticed an improvement in my mental health after taking a break from OptiGUI development.
> 
> I want to add automatic tests to OptiGUI 2.2.0 to make sure that all features work properly, and it doesn't crash (all of which happened in the past). This will take time. Editing 2.1.5 is easy, if the dev env doesn't break (last time, it did)
> 
> That being said, thank you for your patience.

WE are the ones to thank YOU for your work!! I hope you keep on improving your mental health, this comes first and thats what matters! 
Also, thanks for the answer! Hope you have a great end of the year!!

**Comment by opekope2** [comment]
I decided to take some time and update the 2.1.5 (legacy) codebase to 1.20.2 with minimal changes. My original plan was to create an 1.20.2-exclusive build of the 2.1.5 codebase with OptiGlue 1.19.3 merged into it. I'll only make the minimal necessary changes to the codebase+I'll fix #61 in the legacy codebase. This will be released as OptiGUI 2.1.6. The code will be available in a new branch, and won't be merged into main.

**Comment by opekope2** [comment]
![image](https://github.com/opekope2/OptiGUI/assets/20487556/2b91691e-0df8-4057-b318-f3b944195075)

**Comment by Madis0** [comment]
Is CurseForge file still pending approval?

**Comment by opekope2** [comment]
Yes. I released it on Saturday and I don't expect an approval on weekends (everyone needs some time off)
