### ISSUE TITLE
[BUG] OptiGUI doesn't work if gui of horse-like entities was opened twice

### ISSUE THREAD

**Issue by Vi-Tul** [opekope2/OptiGUI#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

OptiGUI working in this scenario

### Actual Behavior

If texture is using Optifine format, it's container=horse and GUI is opened twice in a row while riding a horse, llama, donkey or mule, OptiGUI doesn't apply textures. If dismount and than mount an entity, the texture will be applied, but again only until you reopen the inventory

- Opened once (it's using Oprifine format textures)

![image](https://github.com/opekope2/OptiGUI/assets/92220631/6b52eb9b-845e-48da-beb3-66e69a5379e9)

- Opened twice (now it's using vanilla horse.png texture)

![image](https://github.com/opekope2/OptiGUI/assets/92220631/e5cb6af2-b2a6-4dc9-b8a7-adb12f343349)

### Steps To Reproduce

1. Use texturepack that changes horse/llama/donkey/mule GUI
2. Open horse/llama/donkey/mule GUI while riding it

### Loader and its version

Quilt loader 0.20.2 1.20.1

### OptiGUI version

2.2.0-alpha.1

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
Can confirm, it broke with the 2.2.0 refactoring
