### ISSUE TITLE
[FEATURE REQUEST] Custom overlays

### ISSUE THREAD

**Issue by Angryfishdonut** [opekope2/OptiGUI#78]
Hey! I was just thinking it'd be cool if you could use a resourcepack to add custom overlays to items if they're on your head. Like the pumpkinblur.

so you would need a .properties file and a .png in minecraft/optigui/custom

a .properties file could look something like

overlay=image.png(or file path)
stretch=true (true would stretch the image to fit the screen like the pumpkin, false would black out anything outside the image like the spyglass.
items=iron_helmet, golden_helmet
blur=true

idk how plausible this'd be, but also supporting item renames would be nice, like with CIT mods.

name=ipattern:*knight*

**Comment by opekope2** [comment]
OptiGUI is focused on replacing container GUI textures, not generic ones. I don't plan to add features outside this scope in the foreseeable future.

**Comment by opekope2** [comment]
I might revisit this in the future, maybe in an extension mod, but no guarantees.
