### ISSUE TITLE
[FEATURE REQUEST] Custom mojangstudios logo and colors for resource pack

### ISSUE THREAD

**Issue by GuillaumeFX** [opekope2/OptiGUI#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

![15415805-dadunknown_l](https://github.com/opekope2/OptiGUI/assets/77529874/1e80b971-2eda-4545-8ff3-9d39a55d00df)

### Actual Behavior

‎ 

### Steps To Reproduce

‎ 

### Loader and its version

Fabric loader 0.14.24

### OptiGUI version

2.1.6

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [ ] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
OptiGUI is focused on container GUIs, not splash screens or HUDs. Please check out [Puzzle](https://modrinth.com/mod/puzzle) or [Custom Splash Screen](https://modrinth.com/mod/custom-splash-screen), I believe those already support what you'd like to achieve.
