### ISSUE TITLE
[BUG] Doesn't properly support chest.png in optifine 

### ISSUE THREAD

**Issue by BenignPigeon** [opekope2/OptiGUI#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

In optifine when i have a texture for chest it assigns it to only chests but not with this mod

### Actual Behavior

it doesn't assign the correct texture to the container

### Steps To Reproduce

![image](https://github.com/opekope2/OptiGUI/assets/85837722/84bb0491-32db-41e1-8cf0-1b7c34dbc072)

### Loader and its version

Fabric loader latest

### OptiGUI version

latest

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [X] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
Which version of OptiGUI are you referring to? 2.2.0-alpha.1 (latest alpha) or 2.1.7 (latest stable)?

**Comment by BenignPigeon** [comment]
It was version 2.1.7, however, the bug was only due to the christmas chests that are introduced over christmas time since now it's working correctly

**Comment by opekope2** [comment]
I believe the [date](https://opekope2.github.io/OptiGUI/format.html#date) selector is working properly after a minimal amount of testing (at least, in the upcoming 2.3.0 code)
