### ISSUE TITLE
[BUG] Enchanted Table

### ISSUE THREAD

**Issue by OneWorldStudio** [opekope2/OptiGUI#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

![image](https://github.com/opekope2/OptiGUI/assets/136928305/4787db6f-052f-4e0a-8ae1-14598dc6e9ef)

### Actual Behavior

![image](https://github.com/opekope2/OptiGUI/assets/136928305/52f776fe-ddbf-4b66-b728-65e1584deb84)

### Steps To Reproduce

I downloaded Fabric 1.20.4, installed optigui 2.1.7 and installed the resource pack https://www.planetminecraft.com/texture-pack/arcane-ultimate-enchantment-table-by-shadbie34-v1-0 / , but nothing works

### Loader and its version

Fabric Loader 0.15.3

### OptiGUI version

2.1.7

### Behavior difference

- [X] Behavior is different from OptiGUI documentation
- [X] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

### Anything else

nope

**Comment by opekope2** [comment]
This resource pack doesn't contain OptiFine custom GUIs (`/assets/minecraft/optifine/gui`), so this isn't OptiGUI related.
However, it contains `cit` and `cem` folders, so I recommend downloading mods, which support these features ([see OptiFine alternatives for Fabric](https://fabricmc.net/wiki/community:optifine_alternatives))

**Comment by OneWorldStudio** [comment]
Doesn't work with anything but Optifine, and forge is old and fucked up bullshit

**Comment by opekope2** [comment]
That's probably why the author put **OptiFine required** in the description. I can't provide further assistance.

**Comment by OneWorldStudio** [comment]
((((((((((((((
