### ISSUE TITLE
[BUG] Villager professionselection with Optifine not working

### ISSUE THREAD

**Issue by MulesGaming** [opekope2/OptiGUI#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Each villager profession should get it's own GUI.

### Actual Behavior

All villagers get one (the first alphabetically) profession's GUI. 

### Steps To Reproduce

Download _[Rybo's Enhanced GUI](https://www.planetminecraft.com/texture-pack/rybo-s-enhanced-gui/)_ and get a villager with any profession that's not a armorer. It will show to texture from armorer.png added by this resource pack, not the profession.png that should be assigned. If the armorer.properties file is removed it will show butcher.png and so on. The resource pack works properly with Optifine.

### Loader and its version

Fabric Loader 0.15.2

### OptiGUI version

2.1.7

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [X] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
Interesting. Can confirm. I'll look into fixing this in future versions.
