### ISSUE TITLE
[BUG] villager.type

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/OptiGUI#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior
Work 8)

### Actual Behavior
Not work 8)

### Steps To Reproduce

![image](https://github.com/opekope2/OptiGUI/assets/70120313/07d83b39-f0f6-4b64-b134-87bf2138539c)

### Loader and its version

Fabric Loader 0.15.7 1.20.2 ( and 4)

### OptiGUI version

OptiFUI 2.3.0-alpha.2

### Behavior difference

- [X] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [X] Behavior is different from expected (or straight up doesn't work)

### Anything else

Looks like villager.type isn't filtering properly.
villaget.professions works great.

Thank you for Good Mod!

**Comment by SoulxluoS** [comment]
Looks like the problem here, the filter involves **Type = plains** and compares to **Identifier = minecraft:plains** 
Because Type not containt namespace
![image](https://github.com/opekope2/OptiGUI/assets/70120313/10d97ad9-683f-40b7-84c1-0f858824bd59)

![image](https://github.com/opekope2/OptiGUI/assets/70120313/a39f8890-aa44-410e-9da2-94f6322ae2c6)

**Comment by opekope2** [comment]
Uh well
If `AbstractListSelector<T>.transformInteraction` returned `T?` instead of `Any?`, this would be a compilation error.
But yes, the problem is that it loads an `Identifier`, which will never be equal to a `VillagerType`
