### ISSUE TITLE
[BUG] Biomes Identifier doesn't work with players (will be addressed in upcoming update)

### ISSUE THREAD

**Issue by grebbin** [opekope2/OptiGUI#99]
### Expected Behavior

Hi, I don't know if this is a bug, I couldn't find anything about a change to the biomes identifier, but my texture pack doesn't work properly anymore. I used the biomes identifier to have a unique inventory texture in every biome and it worked in 1.20.4.

### Actual Behavior

Now in 1.20.6 it always shows the normal inventory texture.

### Steps To Reproduce

My ini-file looks like this (excerpt):

```
[player #4]
biomes = ice_spikes
interaction.texture = minecraft:textures/gui/container/inventory.png
replacement = ice_spikes.png

[player #5]
biomes = desert
interaction.texture = minecraft:textures/gui/container/inventory.png
replacement = desert.png
```

And the folder path is \assets\optigui\gui\inventory. All the other textures that I modified using identifiers like villager type still work.

### Loader and its version

Fabric loader 0.15.11-1.20.6

### OptiGUI version

2.3.0-beta.2+1.20.5

### Behavior difference

- [X] OptiGUI documentation
- [ ] OptiFine
- [ ] Something you logically expect from OptiGUI
- [ ] Doesn't work at all

**Comment by opekope2** [comment]
It's not because of 1.20.6, it's because OptiGUI excludes the inventory screen for some reason. I'll look into it. (Note: if you press F12, the default inspector key, the inspector toast will not show)

**Comment by opekope2** [comment]
Players were removed when I reworked the filters. I'll add `player.biomes` instead.
